/**
 * A curated list of domains famous for their early-internet aesthetic. The
 * Wayback CDX query picks a random domain, asks the archive for snapshots
 * inside the requested year range, and returns a real capture URL.
 *
 * These are intentionally US + CN + JP heavy — mixing GeoCities-era personal
 * sites with landmark portals gives a much more interesting wander than
 * just hitting Yahoo every time.
 */
export const SEED_DOMAINS: string[] = [
  "geocities.com",
  "angelfire.com",
  "tripod.com",
  "xanga.com",
  "livejournal.com",
  "myspace.com",
  "friendster.com",
  "lycos.com",
  "altavista.com",
  "excite.com",
  "webring.org",
  "yahoo.com",
  "aol.com",
  "compuserve.com",
  "netscape.com",
  "hotmail.com",
  "icq.com",
  "mirc.com",
  "napster.com",
  "kazaa.com",
  "fanfiction.net",
  "newgrounds.com",
  "homestarrunner.com",
  "ebaumsworld.com",
  "albinoblacksheep.com",
  "somethingawful.com",
  "fark.com",
  "slashdot.org",
  "kuro5hin.org",
  "gamefaqs.com",
  "planetquake.com",
  "planetunreal.com",
  "happytreefriends.com",
  "space.com",
  "salon.com",
  "theglobe.com",
  "pets.com",
  "boo.com",
  "flooz.com",
  "kozmo.com",
  "webvan.com",
  "theonion.com",
  "drudgereport.com",
  // Chinese early web
  "sohu.com",
  "sina.com.cn",
  "163.com",
  "qq.com",
  "baidu.com",
  "chinaren.com",
  "tom.com",
  "xici.net",
  "tianya.cn",
  "mop.com",
  "bokee.com",
  "blogcn.com",
  "hexun.com",
  "tudou.com",
  "56.com",
  "kaixin001.com",
  "renren.com",
  // Japanese early web
  "2ch.net",
  "nicovideo.jp",
  "mixi.jp",
  "rakuten.co.jp",
  "goo.ne.jp",
  "livedoor.com",
  "infoseek.co.jp",
];
